name: Test workflow dispatch inputs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of X to use'
        type: choice
        required: true
        default: '3.0'
        options:
          - '2.6'
          - '3.0'
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print version info
        env:
          VERSION: ${{ github.event.inputs.version }}
          REGISTRY: ghcr.io
          REPOSITORY: learn-github-action
        run: |
          docker build \
              -t ghcr.io/${{ github.repository}}:$VERSION \
              --build-arg ALPINE_VERSION=$VERSION \
              .
          
